# Generated by Django 4.2 on 2023-04-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmatchverification',
            name='count_attempts_in_week',
        ),
        migrations.AddField(
            model_name='user',
            name='count_attempts_in_week',
            field=models.IntegerField(default=0),
        ),
    ]
