# Generated by Django 4.2 on 2023-05-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_history',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
