# Generated by Django 4.2 on 2023-05-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_wish_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wish_history',
            field=models.JSONField(default=list, null=True),
        ),
    ]
