# Generated by Django 4.2 on 2023-05-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_wish_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wish_executed',
            field=models.JSONField(default=list, null=True),
        ),
    ]
