# Generated by Django 4.2 on 2023-05-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_wish_executed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_wish',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
